### ISSUE TITLE
Update readme with compilation guide

### ISSUE THREAD

**Issue by Digitelektro** [Ttl/detector#1]
Dear @Ttl 

I built the PCB of this nice project, but I got stuck at compiling the firmware. Could you please update the readme with how to build the project, which tools needed for that etc. Or a more easy way (for me) if you could release a binary that I can flash/upload straight to the device. 

Thank you!

**Comment by Ttl** [comment]
Sorry, but it's been so long since I last looked at this that I can't remember anymore. Here's some firmware files that might or might not be the correct that I found: [detector.zip](https://github.com/Ttl/detector/files/9717297/detector.zip)

**Comment by Digitelektro** [comment]
Thank you so much! Will try it and get back to you!

**Comment by Digitelektro** [comment]
I tried the firmware, it kinda works. I had to change a python script, I think the firmware version of what you sent is older, but I figured out the problem. I had to remove the packet header check from the script. 
Thanks!
